### ISSUE TITLE
error to mod the rom

### ISSUE THREAD

**Issue by 06112022** [Deijin27/RanseiLink#12]
![e](https://user-images.githubusercontent.com/117556309/200405535-3d76175d-0ef3-4c00-bd8a-5159151b9a66.png)

**Comment by Deijin27** [comment]
On the home screen of the app, if you click the button "Populate Graphics Defaults" and provide it with a rom, then patching should work without issues for you. Let me know how it goes :)

**Comment by 06112022** [comment]
Worked :) Thanks. Mass action are realy usefull, how i can use mass action to other things like put all accuracy to 100 or all warrior stats to a specific number?

**Comment by 06112022** [comment]
do you know how damage calc work in this game?

**Comment by 06112022** [comment]
what "unknow option" and "unknow value" means?

**Comment by Deijin27** [comment]
I've just got to make a small modification to make sure others don't run into the issue you did, then I'll close this. Any more questions in separate issues please. And for more general questions not related to RanseiLink, it may be better to ask in the [RanseiRegionDiscordServer](https://discord.gg/NSCJ4yuRfa)
