### ISSUE TITLE
Editing maps in one mod affects all mods

### ISSUE THREAD

**Issue by BagonGanda** [Deijin27/RanseiLink#18]
when I go into one of my mods in RanseiLink, go to the maps section and do something like move a flame on ignis or remove a log in Aurora, after leaving that mod and checking my others, it appears that the edit is made on all of my other mods.
I do not know what had caused this issue, but it worked normally at one point, then starting doing this.

**Comment by Deijin27** [comment]
Just to confirm, this is happening in 5.2? I thought I fixed this in 5.2.

**Comment by BagonGanda** [comment]
i was not aware of the 5.2 version being released at the time of writing, and after persisting on 5.2, it appears the errors have been mitigated.
