### ISSUE TITLE
Cannot find .dat files

### ISSUE THREAD

**Issue by ShivaD173** [Deijin27/RanseiLink#2]
When I am trying to load the rom, I am getting the error 
`System.IO.FileNotFoundException: data\Pokemon.dat not found in root folder`

Command: `dotnet RanseiConsole.dll loadrom /PATH/TO/FILE/conquest.nds`
OS: MacOS Big Sur
.Net version: 3.1.413

Other commands work fine, but have empty data. 
Also fails with the same error when using the lua command `service:LoadRom([[/PATH/TO/FILE/conquest.nds]])`

**Comment by Deijin27** [comment]
The issue was with using '\\' not working with environment specific path functions. I've been careful to use Path.DirectorySeparatorChar now. It should be addressed in the next release.

**Comment by ShivaD173** [comment]
Resolved in the newest release.
Thank you!
