### ISSUE TITLE
Add dedicated documentation page for editing pokemon sprites, explaining animations

### ISSUE THREAD

**Issue by WhatAUsernameIHave** [Deijin27/RanseiLink#28]

**Comment by Deijin27** [comment]
I dont really understand what you mean, can you give more details and maybe a method of reproduction please?

**Comment by WhatAUsernameIHave** [comment]
For example, if you tried replacing the sprite of a Mon that by default uses an asymmetrical base (like Sewaddle) with a regular battle sprite. It’ll try to use the regular sprite like an asymmetrical one. The checkmark on the Sewaddle page can be either selected or not selected and the same result will occur. This causes the sprite to malfunction in the battle.

**Comment by Deijin27** [comment]
You imported the animation xml from the regular sprite too?

**Comment by WhatAUsernameIHave** [comment]
Ah, I don’t use the .xml way. I just straight import it over the battle sprite. Probably why it was giving me problems lol. Sorry.

**Comment by Deijin27** [comment]
No problem. I've had a few people have issues, I should make a dedicated documentation page for the process.

The animation contains important information to make the sprite work correctly, so if you're changing the checkbox values you will need to change the animation too. Just exporting on from a different pokemon whos animation qualities match your new sprite sheet should do the trick.

**Comment by WhatAUsernameIHave** [comment]
Great, thank you and keep on being awesome!

**Comment by Deijin27** [comment]
Done
https://github.com/Deijin27/RanseiLink/wiki/Image-Editing-Guide
https://github.com/Deijin27/RanseiLink/wiki/Pokemon-Battle-Model-Guide
