### ISSUE TITLE
New Pokémon/Warriors

### ISSUE THREAD

**Issue by DragonHunter70** [Deijin27/RanseiLink#3]
Hi, is it possible/is it planned to be possible to add new pokémon or warriors to the game, and then edit stats and locations? I'm currently looking through the windows forms app and can't see a feature, and i wasn't certain if it could be done with the lua scripting. If this isn't currently in, is it planned to be in the application and if so do you have any ideas when? Thanks. Edit: not really and issue with the app itself, because that has been working really well for me i just wanted to know and didn't know where else to put it.

**Comment by Deijin27** [comment]
There is a lot of barriers to adding additional pokemon and warriors. To take pokemon as an example, 
- the number of pokemon is not stored in the files, it is hard coded, game code would need to be reverse engineered
- even if that was modifyable, we would also be blocked by the fact that the pokemon ids in scenarioPokemon, and in the evolution table are only allocated 8 bits
- then also the code which loads the max link table would also need to be changed

Thus, it's not a focus, it won't happen any time soon.

**Comment by Deijin27** [comment]
They could just put the number of pokemon at the start of the file, and allocate the array length with that. But unfortunately this is not the case. They must have been very certain on having 200 pokemon.

I don't access the code, I only modify the files in the rom file system. Most of the data files are compressed without any information on the compression in the files; I figure out what is in the files using [scripts like this](https://gist.github.com/Deijin27/69926e252c7162c2042317ca6549b721) in RanseiLink Console, using [this tool](https://github.com/Deijin27/ReversePack) to guide me where to look
