### ISSUE TITLE
"Modify Dimensions" on Map tab closes RanseiLink 5.4

### ISSUE THREAD

**Issue by BagonGanda** [Deijin27/RanseiLink#43]
![image](https://user-images.githubusercontent.com/84983046/228666895-70bb0d55-6b55-4555-8aea-9f21504eafdd.png)
It appears that as  you try to modify the dimensions of a map, it will close with this message.

**Comment by Deijin27** [comment]
Closing as duplicate #40

the fix will be in the next release :)
