### ISSUE TITLE
Warrior Recruitment Lock

### ISSUE THREAD

**Issue by Deijin27** [Deijin27/RanseiLink#6]
I actually had another question. I'm having an issue I'm not sure how to resolve. At the very start of the story, when Keiji is trying to teach you how to recruit warriors is when I'm having trouble.

Basically I try to go into the cave with the warrior to recruit and it tells me "This time, all Warriors must be selected in order to go into battle." I am selecting both the units I have and it still prompts me with this message. Not sure what I may have done to mess this up. Any ideas on how to fix this? Thanks!

_Originally posted by @ForgottenIguana in https://github.com/Deijin27/RanseiLink/issues/4#issuecomment-1120502416_

**Comment by Deijin27** [comment]
Maybe the game is checking for specific scenario warrior IDs rather than what it's saying it's looking for in the text. Once we crack the events system hopefully a lot of annoying main story limitations will be gone.

**Comment by Deijin27** [comment]
Can you give details on what you changed?

**Comment by ForgottenIguana** [comment]
Sorry, I wasn't sure if I should make another thread or not.

The only things I've altered are some text files for custom dialogue, some of the Warlord's signature Pokemon, the max links to those Pokemon and the names of the Warlords to custom ones.

**Comment by Deijin27** [comment]
If this is the same mod as you sent last time, I've run the changelist plugin and a possible suspect is:
```xml
<type name="ScenarioWarrior">
    <object name="Scenario_TheLegendOfRansei_Id_18">
      <property name="Class">
        <before>Default</before>
        <after_>ArmyMember</after_>
      </property>
    </object>
    <object name="Scenario_TheLegendOfRansei_Id_19">
      <property name="Class">
        <before>Default</before>
        <after_>ArmyMember</after_>
      </property>
    </object>
  </type>
  ```
 If you've made further changes, send a copy of the current state of your mod.

**Comment by ForgottenIguana** [comment]
It is the same mod as last time, I haven't altered too much since I sent it before except some text files. I'll send it again anyway just in case. I did readjust those changes above back to normal and tested it to no avail again. Looking at my new changelog I have no idea what would continue to cause this issue.

https://github.com/Deijin27/RanseiLink/files/8673968/Pokemon.Legends.Rising.v0.2.zip

**Comment by ForgottenIguana** [comment]
Hey, I just wanted to check in with you to see if there were any updates for this issue. It has been a while and I figured I'd check in to see if there's a fix. If you're still working on it or aren't sure, that's fine. Hope to hear from you soon!

**Comment by Deijin27** [comment]
I've just tried to reproduce this issue with no luck. The only difference from your mod is that I made gallade have much lower hp so it didn't take ages to get to the point where your issue occurred. Video of what happened for me:

https://imgur.com/g5zlf2i

**Comment by Deijin27** [comment]
As a plan of action going forwards, can you:

- Make gallades hp low, zoom through like I did and confirm that the issue is happening for you
- If it is still happening, DM me on discord Deijin#0660 or email deijin27@gmail.com

**Comment by ForgottenIguana** [comment]
I think I found the issue. What I had done originally was I applied the mod to an already modded ROM instead of using a clean one. After watching your video, I decided to try an unchanged ROM and it was successful. I'll make sure to do that from now on. Thanks again for working through this with me!
