### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by Foolaughter** [Deijin27/RanseiLink#62]
### What happened?

message show up when i try to open it, it was fine last time i use it

### Version

5.5

### Error Message

![20231224_144700](https://github.com/Deijin27/RanseiLink/assets/154726270/d30aa501-042c-4390-aee0-de32f7bbe50a)

**Comment by Deijin27** [comment]
If you go to c:\users\username\appdata\local\RanseiLink and delete the settings file it should work.

You may have to delete the settings file each time, there seems to be some issue with the restoring of window dimensions from previous session thats happened to you but not others. I can put in a fix to prevent the crash in the next release.

**Comment by Foolaughter** [comment]
thanks, that fix it
