### ISSUE TITLE
Block of text missing

### ISSUE THREAD

**Issue by TrashMM** [Deijin27/RanseiLink#67]
### What happened?

I´m working on a portuguese patch for the game and just lost the entirety of block 11 all of a sudden, yesterday I was working on 10 and had just finished, then I transalated like 5 or 6 lines of block 11 and then saved before taking a break. Then I just opened the program today and nothing was there, it just jumps from 10 to 12.

Also I've been having another problem where I open the program and it shows a error message and doesn't run, I found a way to bypass this by running the alpha 6.0 before running the 5.5 version and it works, but maybe this problem has a relation with what happened above.

### Version

5.5

### Error Message

![screenshot ](https://github.com/Deijin27/RanseiLink/assets/159511535/a84c14ba-68e3-40a1-81f9-99688f653880)
![screenshot2](https://github.com/Deijin27/RanseiLink/assets/159511535/5351e1ec-136a-43ff-83ac-83c04ced9de7)

**Comment by Deijin27** [comment]
#62 is the startup error you're seeing. I've fixed it and it's coming in the next version.

As for the missing block 11, I'm not sure. I'll investigate tomorrow. 
I would be helpful if you could export the mod you were working on and send it.

**Comment by TrashMM** [comment]
[Portuguese patch v1.zip](https://github.com/Deijin27/RanseiLink/files/14273329/Portuguese.patch.v1.zip)

**Comment by Deijin27** [comment]
I've had a look, and it seems block11 is there, and is approximately the length you would expect, but it's entirely zeros.

I've been unable to reproduce the issue by modifying text and saving. I can't see a regular bug (e.g. related to something you typed in the box) that could cause the file to be like this. It must be a one of those weird random issues with windows corrupting the file, or antivirus, which would be out of my control, but also uncommon.

I'll say just be sure to take regular backups when you've done a lot of work. I'm thinking about adding some validation, automatic backups, etc, to protect against this stuff. Luckily the way the message saving works is that it only saves files you've modified, and each block is saved separately, so it limits the damage in that way.

I've replaced block11 with the original and you're mod looks back to normal.
[Portuguese patch fixed v1.zip](https://github.com/Deijin27/RanseiLink/files/14289455/Portuguese.patch.fixed.v1.zip)

If it happens again let me know.
