### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by RedMageCole** [Deijin27/RanseiLink#78]
### What happened?

First off, wanna say this editor is absolutely fantastic and I've really loved using it- the people working on it did an amazing job! Love the copypaste feature that was added, too!

However, what has happened out of nowhere is that whenever I've tried to open up my project today, I get an error message and RanseiLink shuts down entirely. I'm not sure what it means, so I'm hoping someone can help me diagnose how to fix it without losing all my files.

It was working fine last night: I remember I imported new sprites for a Pokemon and changed the stats and move (and link) of a Legendary Pokemon, if that is related.

This error also does not occur when I load any other mod, so it's most likely project-related.

Thank you!

### Version

6.0

### Error Message

![ransei link whyyyyyyyy](https://github.com/user-attachments/assets/4a831aad-e419-45cf-aa10-02deca7f7f4e)

**Comment by Deijin27** [comment]
Hello. This is the same issue as reported in #77

It was fixed in RanseiLink 6.1. You will see in release notes that manually fixing up pokemon evolutions is needed after updtating. Other than that all should be good.

**Comment by RedMageCole** [comment]
Oh jeez, sorry that I didn't see that- thank you for letting me know! Now that you mention it, I did forget to make a branch evolution, so that explains it... I'll update my version right away! Thanks for letting me know, and again, thank you so much for this absolutely amazing tool, the work you've done is absolutely fantastic!
